impl check_paired_notebooks

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -82,13 +82,30 @@ tasks:
   check_paired_notebooks:
     cmds:
       - |
+        #!/bin/bash
+
         # Check for the existence of corresponding Notebook/Markdown files
         DOCS=$(find docs -name "*.ipynb" | sed 's|^docs/||; s|.ipynb$||' | sort)
         MDS=$(find markdowns -name "*.md" | sed 's|^markdowns/||; s|.md$||' | sort)
         DIFF=$(diff <(echo "$DOCS") <(echo "$MDS")) || true
-        echo "$DIFF"
         if [ -n "$DIFF" ]; then
-          echo "The following notebooks/md files are not paired:"
+          echo "[FAILED] The following notebooks/md files are not paired:"
           echo "$DIFF"
           exit 1
         fi
+
+        # Check for the synchronization between Notebooks and Markdown files
+        ERR=0;
+        while read -r TARG; do
+          LOG=$(uv run jupytext --pre-commit-mode --show-changes --sync $TARG);
+          if [ $? -ne 0 ]; then
+            echo "*** Error while processing ${TARG}";
+            echo "$LOG";
+            ERR=1;
+          fi ;
+        done < <(find docs -name "*.ipynb");
+        if [ $ERR -ne 0 ]; then
+          echo "[FAILED] The notebooks/markdowns are not syncrhonized.";
+          exit $ERR;
+        fi
+        echo "[SUCCESS] All notebooks/markdowns are properly paired and synchronized.";
