Check the error logs at `jupyter-book build` (#11)
# 変更点
- `jupyter-book build` 時にエラーが出た場合にGitHubActionを停止するように変更しました

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main
+  pull_request:
   workflow_dispatch:
 
 permissions:
@@ -38,7 +39,10 @@ jobs:
         run: uv sync --all-extras --dev
 
       - name: Build the book
-        run: uv run jupyter-book build docs
+        run: |
+          uv run jupyter-book build docs
+          ERROR_LOGS=$(find docs/_build -type f -name "*.err.log")
+          if [ -n "$ERROR_LOGS" ]; then while IFS= read -r log; do echo "[ERROR LOG] $log" && cat "$log"; done <<< "$ERROR_LOGS" && exit 1; fi
 
       - name: Upload HTML
         uses: actions/upload-artifact@v4
